# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64, verbose_name='\u63a5\u53e3url')),
                ('description', models.CharField(max_length=64, verbose_name='\u7b80\u4ecb')),
                ('method_type', models.CharField(choices=[('GET', '\u5141\u8bb8Get(\u53ef\u8bfb)'), ('POST', '\u5141\u8bb8POST(\u53ef\u4fee\u6539)'), ('PUT', '\u5141\u8bb8PUT(\u53ef \u521b\u5efa)'), ('HEAD', 'HEAD(\u6682\u4e0d\u7528)'), ('PATCH', 'PATCH(\u6682\u4e0d\u7528)')], max_length=32, verbose_name='\u53ef\u7528\u65b9\u6cd5')),
            ],
            options={
                'verbose_name': '\u63a5\u53e3\u6743\u9650',
                'verbose_name_plural': '\u63a5\u53e3\u6743\u9650',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('server', '\u670d\u52a1\u5668'), ('switch', '\u4ea4\u6362\u673a'), ('router', '\u8def\u7531\u5668'), ('firewall', '\u9632\u706b\u5899'), ('storage', '\u5b58\u50a8\u8bbe\u5907'), ('acc_cpu', 'CPU'), ('acc_memory', '\u5185\u5b58\u6761'), ('acc_disk', '\u786c\u76d8'), ('acc_network_adapter', '\u7f51\u5361'), ('acc_monitor', '\u663e\u793a\u5668'), ('acc_others', '\u5176\u5b83\u914d\u4ef6')], default='server', max_length=64)),
                ('name', models.CharField(max_length=30)),
                ('hostname', models.CharField(blank=True, max_length=32, unique=True)),
                ('asset_op', models.CharField(blank=True, max_length=32, null=True)),
                ('trade_time', models.DateTimeField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('warranty', models.SmallIntegerField(blank=True, null=True, verbose_name='\u4fdd\u4fee\u671f')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='\u4ef7\u683c')),
                ('function', models.CharField(blank=True, max_length=32, null=True)),
                ('cabinet_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u673a\u67dc\u53f7')),
                ('cabinet_order', models.SmallIntegerField(blank=True, max_length=30, null=True, verbose_name='\u673a\u67dc\u4e2d\u5e8f\u53f7')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Init'), (2, 'Standby'), (3, 'Online'), (4, 'Offline'), (5, 'Unreachable'), (6, 'Deprecated'), (7, 'Maintenance')], null=True, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7\u603b\u8868',
                'verbose_name_plural': '\u8d44\u4ea7\u603b\u8868',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u4e1a\u52a1\u7ebf')),
                ('memo', models.CharField(blank=True, max_length=64, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1\u7ebf',
                'verbose_name_plural': '\u4e1a\u52a1\u7ebf',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definded_raid_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u9884\u5b9a\u4e49raid\u7c7b\u578b')),
                ('os_installed', models.BooleanField(default=1)),
                ('puppet_installed', models.BooleanField(default=1)),
                ('zabbix_configured', models.BooleanField(default=1)),
                ('auditing_configured', models.BooleanField(default=1)),
                ('approved', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=64, unique=True, verbose_name='\u5408\u540c\u53f7')),
                ('name', models.CharField(max_length=64, verbose_name='\u5408\u540c\u540d\u79f0')),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('cost', models.IntegerField(verbose_name='\u5408\u540c\u91d1\u989d')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('license_num', models.IntegerField(blank=True, verbose_name='license\u6570\u91cf')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5408\u540c',
                'verbose_name_plural': '\u5408\u540c',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=64, verbose_name='SN\u53f7')),
                ('parent_sn', models.CharField(blank=True, max_length=128, unique=True)),
                ('manufactory', models.CharField(blank=True, default=None, max_length=32, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=64, verbose_name='CPU\u578b\u53f7')),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': 'CPU\u90e8\u4ef6',
                'verbose_name_plural': 'CPU\u90e8\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, verbose_name='SN\u53f7')),
                ('parent_sn', models.CharField(blank=True, max_length=128)),
                ('slot', models.CharField(blank=True, max_length=32, verbose_name='\u63d2\u69fd\u4f4d')),
                ('manufactory', models.CharField(blank=True, default=None, max_length=32, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='\u78c1\u76d8\u578b\u53f7')),
                ('capacity', models.FloatField(blank=True, verbose_name='\u78c1\u76d8\u5bb9\u91cfGB')),
                ('iface_type', models.CharField(blank=True, choices=[('SATA', 'SATA'), ('SAS', 'SAS'), ('SCSI', 'SCSI'), ('SSD', 'SSD')], max_length=64, verbose_name='\u63a5\u53e3\u7c7b\u578b')),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u786c\u76d8\u90e8\u4ef6',
                'verbose_name_plural': '\u786c\u76d8\u90e8\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True, verbose_name='\u8bf7\u6c42ID')),
                ('post_data', models.TextField(blank=True, verbose_name='\u8bf7\u6c42Data')),
                ('detail', models.TextField(blank=True, verbose_name='\u8be6\u7ec6\u63cf\u8ff0')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u673a\u623fenglish')),
                ('display_name', models.CharField(default=None, max_length=32, verbose_name='\u4e2d\u6587\u663e\u793a\u540d')),
                ('region', models.CharField(default=None, max_length=64, verbose_name='\u533a\u57df')),
                ('region_display_name', models.CharField(default=None, max_length=64, verbose_name='\u533a\u57df\u4e2d\u6587')),
            ],
        ),
        migrations.CreateModel(
            name='Maintainence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u4e8b\u4ef6\u540d\u79f0')),
                ('maintain_type', models.SmallIntegerField(choices=[(1, '\u786c\u4ef6\u66f4\u6362'), (2, '\u65b0\u589e\u914d\u4ef6'), (3, '\u8bbe\u5907\u4e0b\u7ebf'), (4, '\u8bbe\u5907\u4e0a\u7ebf'), (5, '\u5b9a\u671f\u7ef4\u62a4'), (6, '\u4e1a\u52a1\u4e0a\u7ebf\\\u66f4\u65b0\\\u53d8\u66f4'), (7, '\u5176\u5b83')], max_length=30, verbose_name='\u53d8\u66f4\u7c7b\u578b')),
                ('description', models.TextField(verbose_name='\u4e8b\u4ef6\u63cf\u8ff0')),
                ('device_sn', models.CharField(blank=True, max_length=64, verbose_name='AssetID')),
                ('event_start', models.DateTimeField(blank=True, verbose_name='\u4e8b\u4ef6\u5f00\u59cb\u65f6\u95f4')),
                ('event_end', models.DateTimeField(blank=True, verbose_name='\u4e8b\u4ef6\u7ed3\u675f\u65f6\u95f4')),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u53d8\u66f4\u7eaa\u5f55',
                'verbose_name_plural': '\u53d8\u66f4\u7eaa\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u5382\u5546\u540d\u79f0')),
                ('support_num', models.CharField(blank=True, max_length=30, verbose_name='\u652f\u6301\u7535\u8bdd')),
                ('memo', models.CharField(blank=True, max_length=30, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u5382\u5546',
                'verbose_name_plural': '\u5382\u5546',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, verbose_name='SN\u53f7')),
                ('parent_sn', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=64, verbose_name='\u578b\u53f7')),
                ('manufactory', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5236\u9020\u5546')),
                ('slot', models.CharField(blank=True, max_length=32, verbose_name='\u63d2\u69fd\u4f4d')),
                ('capacity', models.FloatField(blank=True, verbose_name='\u5bb9\u91cf')),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5185\u5b58\u90e8\u4ef6',
                'verbose_name_plural': '\u5185\u5b58\u90e8\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=64, unique=True, verbose_name='SN\u53f7')),
                ('manufactory', models.CharField(default=None, max_length=32, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(max_length=64, verbose_name='\u663e\u793a\u8bbe\u5907\u578b\u53f7')),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Asset')),
            ],
            options={
                'verbose_name': '\u663e\u793a\u8bbe\u5907',
                'verbose_name_plural': '\u663e\u793a\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=64, unique=True, verbose_name='SN\u53f7')),
                ('manufactory', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u578b\u53f7')),
                ('port_num', models.SmallIntegerField(verbose_name='\u7aef\u53e3\u4e2a\u6570')),
                ('device_detail', models.TextField(verbose_name='\u8bbe\u7f6e\u8be6\u7ec6\u914d\u7f6e')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Asset')),
            ],
            options={
                'verbose_name': '\u7f51\u7edc\u8bbe\u5907',
                'verbose_name_plural': '\u7f51\u7edc\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='\u63d2\u53e3')),
                ('sn', models.CharField(blank=True, max_length=128, verbose_name='SN\u53f7')),
                ('parent_sn', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='\u7f51\u5361\u578b\u53f7')),
                ('manufactory', models.CharField(blank=True, max_length=32, verbose_name='\u5236\u9020\u5546')),
                ('ipaddr', models.GenericIPAddressField(verbose_name='ip\u5730\u5740')),
                ('mac', models.CharField(max_length=64, verbose_name='\u7f51\u5361mac\u5730\u5740')),
                ('netmask', models.CharField(blank=True, max_length=64)),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u7f51\u5361\u90e8\u4ef6',
                'verbose_name_plural': '\u7f51\u5361\u90e8\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u4ea7\u54c1\u578b\u53f7')),
                ('version', models.CharField(blank=True, max_length=64, verbose_name='\u4ea7\u54c1\u7248\u672c\u53f7')),
            ],
        ),
        migrations.CreateModel(
            name='RaidAdaptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, verbose_name='SN\u53f7')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='\u63d2\u53e3')),
                ('parent_sn', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=64, verbose_name='\u578b\u53f7')),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='auto', max_length=32)),
                ('sn', models.CharField(max_length=64, verbose_name='SN\u53f7')),
                ('manufactory', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u578b\u53f7')),
                ('cpu_count', models.SmallIntegerField(blank=True, verbose_name='cpu\u4e2a\u6570')),
                ('cpu_core_count', models.SmallIntegerField(blank=True, verbose_name='cpu\u6838\u6570')),
                ('raid_type', models.TextField(blank=True, verbose_name='raid\u7c7b\u578b')),
                ('ram_size', models.IntegerField(blank=True, verbose_name='\u5185\u5b58\u603b\u5927\u5c0fGB')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Asset')),
                ('cpu_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.CPU')),
                ('nic', models.ManyToManyField(to='app01.NIC', verbose_name='\u7f51\u5361\u5217\u8868')),
                ('physical_disk_driver', models.ManyToManyField(blank=True, to='app01.Disk', verbose_name='\u786c\u76d8')),
                ('raid_adaptor', models.ManyToManyField(blank=True, to='app01.RaidAdaptor', verbose_name='Raid\u5361')),
                ('ram', models.ManyToManyField(blank=True, to='app01.Memory', verbose_name='\u5185\u5b58\u914d\u7f6e')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668',
                'verbose_name_plural': '\u670d\u52a1\u5668',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.SmallIntegerField(choices=[(1, 'GNU/Linux'), (2, 'MS/Windows'), (3, 'Network Firmware'), (4, 'Softwares')], help_text='eg. GNU/Linux', max_length=64, verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
                ('version', models.CharField(help_text='eg. CentOS release 6.5 (Final)', max_length=64, unique=True, verbose_name='\u8f6f\u4ef6/\u7cfb\u7edf\u7248\u672c')),
            ],
            options={
                'verbose_name': '\u8f6f\u4ef6/\u7cfb\u7edf',
                'verbose_name_plural': '\u8f6f\u4ef6/\u7cfb\u7edf',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('token', models.CharField(max_length=128, verbose_name='token')),
                ('department', models.CharField(max_length=32, verbose_name='\u90e8\u95e8')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=32, verbose_name='\u5ea7\u673a')),
                ('mobile', models.CharField(max_length=32, verbose_name='\u624b\u673a')),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('backup_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_backup_name', to='app01.UserProfile', verbose_name='\u5907\u7528\u8054\u7cfb\u4eba')),
                ('business_unit', models.ManyToManyField(to='app01.BusinessUnit')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserProfile', verbose_name='\u4e0a\u7ea7\u9886\u5bfc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='server',
            name='software',
            field=models.ManyToManyField(blank=True, null=True, to='app01.Software', verbose_name='\u8f6f\u4ef6'),
        ),
        migrations.AlterUniqueTogether(
            name='raidadaptor',
            unique_together=set([('parent_sn', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together=set([('name', 'mac')]),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='firmware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Software'),
        ),
        migrations.AlterUniqueTogether(
            name='memory',
            unique_together=set([('parent_sn', 'slot')]),
        ),
        migrations.AddField(
            model_name='maintainence',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_user', to='app01.UserProfile', verbose_name='\u53d1\u8d77\u4eba'),
        ),
        migrations.AddField(
            model_name='maintainence',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserProfile', verbose_name='\u6267\u884c\u4eba'),
        ),
        migrations.AlterUniqueTogether(
            name='disk',
            unique_together=set([('parent_sn', 'slot')]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Software', verbose_name='OS'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='primary_ip',
            field=models.ManyToManyField(blank=True, to='app01.NIC', verbose_name='\u7f51\u5361\u5217\u8868'),
        ),
        migrations.AddField(
            model_name='asset',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app01.UserProfile', verbose_name='\u8bbe\u5907\u7ba1\u7406\u5458'),
        ),
        migrations.AddField(
            model_name='asset',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.BusinessUnit', verbose_name='\u5c5e\u4e8e\u7684\u4e1a\u52a1\u7ebf'),
        ),
        migrations.AddField(
            model_name='asset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserProfile', verbose_name='\u4e1a\u52a1\u4f7f\u7528\u65b9'),
        ),
        migrations.AddField(
            model_name='asset',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Contract', verbose_name='\u5408\u540c'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.IDC', verbose_name='IDC\u673a\u623f'),
        ),
        migrations.AddField(
            model_name='apiauth',
            name='users',
            field=models.ManyToManyField(null=True, to='app01.UserProfile'),
        ),
        migrations.AlterIndexTogether(
            name='server',
            index_together=set([('sn', 'asset')]),
        ),
        migrations.AlterUniqueTogether(
            name='apiauth',
            unique_together=set([('url', 'method_type')]),
        ),
    ]
