# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Username', models.CharField(help_text=b'bu yao du bo', max_length=10)),
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
